name: Build & Unit Tests

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'release/*'

jobs:
    build:
        name: Build & Test

        runs-on: [macos-13]
    
        defaults:
          run:
            shell: zsh {0}

        concurrency: 
          group: build-${{ github.ref }}
          cancel-in-progress: true

        env:
          XCODE_VERSION_PATH: /Applications/Xcode_14.3.1.app
          TEST_DESTINATION: platform=iOS Simulator,name=iPhone 14,OS=latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Xcode version
            # See available versions & paths: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
            run: sudo xcode-select -s ${{ env.XCODE_VERSION_PATH }}
    
          - name: Build Package
            run: xcrun xcodebuild build -scheme GXUITest -destination "generic/platform=iOS Simulator" -quiet
    
          - name: Run package tests
            run: xcrun xcodebuild test -scheme GXUITest -destination "${{ env.TEST_DESTINATION }}" -quiet
