name: Build & Test

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'release/*'

jobs:
    build:
        name: Build & Test

        runs-on: [macos-13]
    
        defaults:
          run:
            shell: zsh {0}

        concurrency: 
          group: build-${{ github.ref }}
          cancel-in-progress: true

        env:
          XCODE_VERSION_PATH: /Applications/Xcode_14.3.1.app
          TEST_DESTINATION: platform=iOS Simulator,name=iPhone 14,OS=latest
          INTEGRATION_TESTS_RESULTS_PATH: /tmp/UITestingSampleApp.xcresult

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Xcode version
            # See available versions & paths: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
            run: sudo xcode-select -s ${{ env.XCODE_VERSION_PATH }}
    
          - name: Build Package
            run: xcrun xcodebuild build -scheme GXUITest -destination "generic/platform=iOS Simulator" -quiet
    
          - name: Run package tests
            run: xcrun xcodebuild test -scheme GXUITest -destination "${{ env.TEST_DESTINATION }}" -quiet

          # Disable integration tests since they cannot run on GitHub Actions (apprarantly, VMs don't have enought resources and the simulator times out)
          # - name: Run integration tests
          #   working-directory: Tests/IntegrationTests/UITestingSampleApp
          #   run: xcrun xcodebuild -scheme UITestingSampleApp clean test -testPlan UITestingSampleApp -destination "${{ env.TEST_DESTINATION }}" -resultBundlePath "${{ env.INTEGRATION_TESTS_RESULTS_PATH }}" -quiet

          # - name: Zip integration tests results
          #   if: ${{ failure() }}
          #   run: ditto -c -k --sequesterRsrc --keepParent "${{ env.INTEGRATION_TESTS_RESULTS_PATH }}" "${{ env.INTEGRATION_TESTS_RESULTS_PATH }}.zip"

          # - name: Upload integration tests results
          #   if: ${{ failure() }}
          #   uses: actions/upload-artifact@v3
          #   with:
          #     name: integration-tests-results.zip
          #     path: ${{ env.INTEGRATION_TESTS_RESULTS_PATH }}
